### ISSUE TITLE
Add blog to website

### ISSUE THREAD

**Issue by robinske** [scalabridge/organization#3]

**Comment by jarrodu** [comment]
Maybe this issue should be moved to the website repo. If someone looks at the website repo and is looking for a way to help out they may not discover this issue.

Would converting the website to a [Jekyll](https://jekyllrb.com/) site be an improvement? It would make it easy to add a blog and the blog posts could be drafted in Markdown. The only hiccup is that it requires Ruby. I am thinking of Jekyll mostly because it is pretty easy and I am already familiar with it.
